### ISSUE TITLE
`.gitignore` `data/backup` csvs for now to try to avoid merge conflicts.

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#101]
making an issue as reminder to change back after

**Comment by NewGraphEnvironment** [comment]
right. doesn't work because we are tracking those files already.  will just try to pick around and not commit them and  turn `backup = FALSE` where it is redundant.  If we do commit - should be fine to deal with the conflicts

**Comment by newgraph-lschick** [comment]
just saw this now. Hoping my PR doesn't have any conflicting csvs😬
