### ISSUE TITLE
put stock assessment data into one large filterable table

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#107]
too many tables when split by watershed group.  being able to filter will be really helpful for more than just the watershed

**Comment by NewGraphEnvironment** [comment]
@lucy-schick -  you could do this as per the method in nrp-vis-2024 . copy local gt interactive table function and replace all tables with just  1 (total) large filterable table somewhere appropriate in background.  Put into gitbook_on = TRUE chunk and put gitbook_on conditional statement for pdf pointing pdf user to online report.

**Comment by lucy-schick** [comment]
got a draft that can be found here https://github.com/lucy-schick/fish_passage_skeena_2023_reporting/blob/final_memo/0200-background.Rmd#L227C1-L259C4

things that still need to be done/figured out:
- change theme to match other tables, info here https://gt.rstudio.com/reference/data_color.html?q=themes#color-palette-access-from-paletteer
- make column widths to match header widths, i think we can use this https://gt.rstudio.com/reference/cols_width.html?q=column%20wi#null
- cross refencing still not working, should be possible, issue here tho https://github.com/rstudio/gt/issues/818

**Comment by NewGraphEnvironment** [comment]
looks like `total_return_to_river` filter has us losing everything after 1997 so will remove that filter

caption provided with `ltab_caption()` function

**Comment by lucy-schick** [comment]
okay nevermind I see whats going on now. The `All Areas NuSEDS.csv` in the Skeena repo had already been filtered to only contain waterbodies in the study area (this was done here http://htmlpreview.github.io/?https://github.com/NewGraphEnvironment/restoration_wedzin_kwa_2024/blob/main/memos/dfo_stock_assess.html) and then copied over.

I will redo this process for the fraser repo. Maybe we could rename `All Areas NuSEDS.csv` so its clear that it contains only the waterbodies in the study area?

**Comment by NewGraphEnvironment** [comment]
Most important thing is not to try to commit an oversized file to GitHub as that can be a huge pain to deal with. Resizing the original file without renaming it is one way to not have a straggler file that can be accidentally committed. Obviously many ways to deal with the same issue though (.gitignore, script removing original download completely after filter/rename, store original file on cloud like aws vs locally, Etc) so as long as it is dealt with, clearly documented and consistent (not requiring custom name choice prone to errors every time)- renaming filtered file works.
