### ISSUE TITLE
submit fish data to province

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#122]
First step is to follow all the steps we did for the peace as per this issue 

hopefully it isn't too weird a process to follow and there aren't too many project specific idiosyncracies.  Now that it has been realized that we don't need to ammend reference numbers or method numbers it is much more straight forward.

https://github.com/NewGraphEnvironment/fish_passage_peace_2023_reporting/issues/62 and associated links back to the template in https://github.com/NewGraphEnvironment/fish_passage_template_reporting/tree/main/scripts/03_permit_submission

**Comment by NewGraphEnvironment** [comment]
provincial permit ID is SM23-814011 (used within spreadsheet and for nameing of excel file)

dfo permit (because sallmon are involved)  is XR 422 2023 - we don't need this one yet but will do once we have the data finalized as we include it in an email to the submission to DFO.NCSP-PSCN.MPO@dfo-mpo.gc.ca with links to reporting

**Comment by lucy-schick** [comment]
There’s a note saying the `whse_fish.wdic_waterbody_route_line_svw`  layer has been added to the skeena 2023 project but I can’t seem to find it there, and checked the background layer geopackage and not there either. Just wondering if you added the `whse_fish.wdic_waterbody_route_line_svwlayer` to the skeena project and forgot to sync?

**Comment by NewGraphEnvironment** [comment]
include all data possible in original fds and run backup so we can view on github

**Comment by NewGraphEnvironment** [comment]
round feature hieght/lenght to nearest m.  Ensure height and length present. Remove bridge features (thing called pscis for that type of data)
