### ISSUE TITLE
Phase 1 submission validation errors

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#13]
The following are errors that resulted from validating `pscis_phase1.xlsm`:

1. - [x] Rail site on modelled crossing 8302869 Gershwin Creek - Length can not be over 100 (changed to 99 and added note in comments)

2. - [x] Site 8300013 is missing barrel photo - culvert was submerged and couldn't get a photo

3. - [x] Site 8300094 is missing outlet photo - could not find outlet

4. - [x] Site 8300756 is missing upstream photo - I think I just forgot to take this photo for some reason

5. - [x] Site 8801379 is missing downstream photo (missed this one when sorting photos into folders by hand)

6. - [x] Project budget and funding source need to be filled out on cover page

NOTE: error 1 and 5 have been fixed in [PR #12](https://github.com/NewGraphEnvironment/fish_passage_skeena_2023_reporting/pull/12)

**Comment by Mateo9569** [comment]
Just added the `no_photo_` images to site folders for 2, 3 and 4

**Comment by NewGraphEnvironment** [comment]
going to try to submit assuming no validation errors in the PSCIS form based on this and give submission a try.

Otherwise need to load into windows machine to do the validation. will just try and see if it lands

**Comment by NewGraphEnvironment** [comment]
hmm.  can't even generate submission on Mac.  time to dust off the old windows machine.  what a pain. will do validation at same time
