### ISSUE TITLE
8800140 - Tributary to Skeena River

### ISSUE THREAD

**Issue by newgraph-lschick** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#28]
- [x] gps way point ~33m from culvert and modelled crossing
- [x] @NewGraphEnvironment to review/check spelling of comments because I am not familiar enough with the lingo yet to correct voice-to-text

**Comment by NewGraphEnvironment** [comment]
> gps way point ~33m from culvert and modelled crossing
reasonable

comments seems reasonable
