### ISSUE TITLE
8547 tributary to McDonell Lake 

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#3]
Perhaps our best lower cost opportunity in the Zymoetz to date...
**Lucy's edits in bold**

No `form_pscis` paper card, digital card or photos, **everything is there now, photos, form_pscis.**  No photos in historic PSCIS data.  Looks like we have a coincidental outlet photo but none of the other data or photos. Will need to scab a submission - uh

- [x] First FISS site `8547_us_ef3` should be `8547_ds_ef3` (will change in geopackage)
- [ ] sockeye point identified as "spawning location" downstream
- [ ] FISS site (8214)
- [ ] unaccessible 9.8 ha of lake and 3.1 ha of wetland mapped upstream
- [ ] additional habitat site surveyed at modelled crossing 24600461 (we will of course use pscis ID once we have one)
- [ ] need to minus 240m from `downstream_route_measure` to give BOTH crossing locations on stream b/c freshwater atlas lines are measured from centreline of lake (ex. The culvert on McDonnel Lake FSR is located  `r `downstream_route_measure` - 240` m upstream from McDonell Lake. ds crossing 24600461 (PSCIS) is located `r `downstream_route_measure` - 240` m from McDonell Lake.  Not sure it needs to be coded but it should be accurate
- [ ] Mike Risdale mentioned historic mine in the area. we need to track down some info.  i think I saw a mine remediation site driving by.  Might send him a text. may be mentioned in reconnaissance fish reports. **Lucy has done some searching (using both Zymoetz and Copper river terms) and can't find any info about a mine.**
- [ ] zymoetz used to be named Copper River so we search and watch for alternative names in background docs

Lucy's notes:
- [ ] Mateo's gps points but Mateo is not listed as a crew member at this site, crew_members are AR and AF, is this Andy and Alicia? Camera_id and gps_id are for andyr, so I'm guessing they just used mateos gps and that this is not an issue.
- [ ]  Added mention of CT fish obs (from ef sheets) into comments.
- [ ]  photos seem all over the place. Photos tagged with keywords all show a frozen/icy stream and don't have a datestamp. First thought was that these are from the initial phase 1 assessment but PSCIS says that was done in 2010 by TIMBER SALES MANAGER SKEENA, not us... lots of photos from Sept 20/2023 showing greenery/not frozen stream during ef surveys. Not much of an issue more just an observation.

**Comment by NewGraphEnvironment** [comment]
Alicia and Andy did cv assessment as we forgot

**Comment by lucy-schick** [comment]
memo written up here https://github.com/NewGraphEnvironment/fish_passage_skeena_2023_reporting/blob/main/0800-appendix-8547-mcdonell.Rmd
