### ISSUE TITLE
198022 - Tributary to Tagit Creek

### ISSUE THREAD

**Issue by newgraph-lschick** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#30]
- [x] Unsure about comments in bold: "Moderate value habitat. Habitat confirmation conducted on stream, walked from upstream crossing down through wetland type area to culvert. Mostly dewatered besides small section above this crossing and below the upper crossing. **Surveyed from upstream to down and ended up on road approximately 40 m to the north**. Stream seems to merge with wetland type area just upstream of the road. Fish sampling conducted with dolly varden captured in small (2.5m2) outlet pool. Cutthroat are known to be upstream of crossing."

Survey sites don't line up with comments and unsure if **bold** comment is supposed to be describing the downstream surveyed site but that doesn't align with "ending up on road 40m north". There is another site #29 more north up the road but its ~170m away so I don't think this is what they are referring to.

**Comment by NewGraphEnvironment** [comment]
all good to leave. gps track shows what happened.  was basically a disclaimer that missed a bit of the channel as it was tough to follow. might have been better in hab con comments (assuming is there too)
