### ISSUE TITLE
198225 - Sterritt Creek

### ISSUE THREAD

**Issue by lucy-schick** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#35]
This site seems odd to me:
- This crossing was already assessed in 2022 and has a natural falls which ranks as a barrier
- There is a crossing just downstream that is still unassessed
- when looking at the photos in the [pscis database for site 198225](https://a100.gov.bc.ca/pub/pscismap/imageViewer.do?assessmentId=199405), the road card has the modelled crossing id for the downstream site (`8300128`) but in the `pscis assessment layer` the site is linked to the upstream site (modelled crossing id = `8302239`), maybe its linked to the wrong crossing.
- The culvert/gps point is much closer to the downstream crossing than the upstream crossing.
- the photos in the folder are the same as some of the ones in the pscis database
- there is no mention of a natural falls in the pscis database site... but the photos look identical to the ones taken at the natural falls.

Here is what I think happened:

- [ ] In 2022 the modelled crossing `8300128` was assessed but bcfishpass linked it to the upstream modelled crossing `8302239`. Need to change this using https://github.com/NewGraphEnvironment/bcfishpass/blob/main/data/pscis_modelledcrossings_streams_xref.csv
- [ ] in 2023 MW re-assessed modelled crossing `8300128` because it was modelled as un-assessed due to the incorrect linking mentioned above. But put the pscis id `198225` as the site number? Still not totally sure what happened here.

![Screen Shot 2024-03-18 at 9 30 18 AM](https://github.com/NewGraphEnvironment/fish_passage_skeena_2023_reporting/assets/151881303/d4de4311-c817-42a4-bea4-72dd796508de)
![Screen Shot 2024-03-18 at 9 31 11 AM](https://github.com/NewGraphEnvironment/fish_passage_skeena_2023_reporting/assets/151881303/1de4a2a6-2502-48e0-9811-0e927967f3cb)

**Comment by NewGraphEnvironment** [comment]
https://www.newgraphenvironment.com/fish_passage_skeena_2022_reporting/sterritt-creek---198225---appendix.html

what happened? - Prioritized after 2022 field work.  During habitat confirmation in 2022 the survey crew did not recognize the falls at the crossing outlet as a fish passage issue that would not be rectified by replacing the culvert with a bridge. We went back in 2023 to sample to see what fish were using the system upstream and down and fortunately noticed the outlet drop/falls/cascade thing before fishing so called off the prioritization

- [x] update assessment_comments to tell this story

> In 2022 the modelled crossing 8300128 was assessed but bcfishpass linked it to the upstream modelled crossing 8302239. 

8302239 is on the correct road.

- [x] 8300128 is not present and so should be removed in https://github.com/NewGraphEnvironment/bcfishpass/blob/main/data/user_modelled_crossings_fixes.csv (should have been done last year but doesn't really affect modelling much anyway). Done.

> the photos in the folder are the same as some of the ones in the pscis database
1 year newer.  changed outlet and downstream photos (used ones from my camera) to better show the outlet drop and downstream canyon

- [x] `road_tenure` should have the `map_label` appended to the tenure holder NORTHPAC FOREST LICENCE INC. (Norpac R03780 6 )


Need to update 2022 report with text and photos about what happened. Will make issue there and link to here. All changes made so will close on commit
