### ISSUE TITLE
8300756 - Tributary to Skeena River

### ISSUE THREAD

**Issue by newgraph-lschick** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#38]
- [x] added mention of small outlet drop (from photos) and changed comments to say not a **major** barrier to fish passage, because the outlet drop could be a barrier to some life stages. 
- [x] added mention on historic CT FISS sites upstream and downstream, as well as fry spotted during assessment of downstream crossing.

**Comment by NewGraphEnvironment** [comment]
- [x] Small road/trail between highway and outlet, culvert runs underneath both.  Will remove 8302959 from `bcfishpass` modelling

> has a small outlet drop, but does not appear to be a major fish passage issue. 

- [x] from the photos we can see that the outlet drop is muuuch bigger than 5cm. Will revise to be 20cm, add note about estimate from photo in comments and remove the not about not a major fish passage issue.
