### ISSUE TITLE
8300013 - Gershwin Creek

### ISSUE THREAD

**Issue by newgraph-lschick** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#41]
- [x] Nearby crossings have fish obs, downstream crossing has very high value habitat. Seems like this stream likely has fish. Added to comments, "Good candidate for replacement given the surrounding crossings have fish observations and good habitat."

**Comment by NewGraphEnvironment** [comment]
mmm. just a wee little guy. will swap with mainstem Gershwin crossing on railway for follow up 8302869 - Gershwin Creek here https://github.com/NewGraphEnvironment/fish_passage_skeena_2023_reporting/issues/24
