### ISSUE TITLE
24601280 - Tributary to Zymoetz River

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#52]
in QGIS and past versions of Phase 1 file but currently missing from PSCIS submission forms.  This is both a phase 1 and phase 2 site (ie. has assessment info but also detailed habitat data ~~and fish sampling data~~ in FDS template)

**Comment by newgraph-lschick** [comment]
This site it is in `pscis_phase1.xlsm` but after reading your comment it sounds like it should be in `pscis_phase2.xlsm`. Shall I move it over?

![Screen Shot 2024-04-03 at 8 54 06 AM](https://github.com/NewGraphEnvironment/fish_passage_skeena_2023_reporting/assets/151881303/e03b2aef-33f6-41b7-b543-f18022563030)

**Comment by NewGraphEnvironment** [comment]
nice - no - all good. didn't see it there. thats great. 

 It will actually be in both the spreadsheets but will get the pscis Id in the phase 2 sheet once it gets assigned (see https://www2.gov.bc.ca/assets/gov/environment/natural-resource-stewardship/land-based-investment/forests-for-tomorrow/pscis-user-guide-v2.pdf ). 

Changing all these spreadsheets right now so no thanks on the edits!

**Comment by lucy-schick** [comment]
Confirming that the site is in both pscis phase 1 and phase 2 spreadsheets (under PSCIS ID in phase 2). Will close.
