### ISSUE TITLE
Sites to move from Phase 2 file to reassessments submission templates

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#56]
all sites where hab cons were done in past years and therefore have memo .  Usually revisited to do fish sampling so grabbed culvert again while there

easy ref of skeena/bulk reports here https://www.newgraphenvironment.com/project/aquatic_restoration_planning/

made issues which should add up eventually here

- [x] https://github.com/NewGraphEnvironment/fish_passage_skeena_2022_reporting/issues/130 
- [x] https://github.com/NewGraphEnvironment/fish_passage_skeena_2021_reporting/issues/47
- [x] https://github.com/NewGraphEnvironment/fish_passage_bulkley_2020_reporting/issues/39

**Comment by newgraph-lschick** [comment]
https://github.com/NewGraphEnvironment/fish_passage_skeena_2022_reporting/issues/130 are top priority
