### ISSUE TITLE
14000855 (PSCIS 198940) - 14000575 (PSCIS 198935) Tributary to Morice River

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#57]
Should actually be a Tributary to Knapper Creek

Options to fix 
1. fix in QGIS and re-export to submission template to build report
2. one off fixes in submission spreadsheet

**Comment by NewGraphEnvironment** [comment]
lets fix stream name in qgis and submission spreadsheet then close

**Comment by lucy-schick** [comment]
fixed in QGIS and pscis phase 1 spreadsheet
