### ISSUE TITLE
Add electrofishing site data to `habitat_confirmations.xls`

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#64]
some documentation of this process here. https://github.com/NewGraphEnvironment/fish_passage_template_reporting/issues/8

Sites were only enclosed at Thompson downstream sites which also have a second pass on the following day. We tested our efficiency by seeing how many of our captured fish had tags the next day (ie. we put the fish back into our enclosed sites after our first pass and fished them again the next day)

NOTE - for Thompson `h/p` should not be 2 teh second day since the fish were put back in.  Also - the downstream sites were enclosed. `temperature`, `conductivity` and `Turbidity` were likely different second day too  - card will tell us - should be recorded

**Comment by NewGraphEnvironment** [comment]
Actually - I think we are going to need to leave h/p as 2 for Thompson second day to avoid other complexity. We can just put a note in Step 2 that fish were returned to the site after the first pass.

**Comment by newgraph-lschick** [comment]
A couple sites that were a bit funky and have missing data:

- [ ] `8478_us` - Trib to McDonell Lake
  - local name and site card missing _ef but everything else looks like an ef site. 
  - site card is a bit confusing... has a length written at the bottom which is different than in `form_fiss`


- [ ] `8478_ds_ef1` - Trib to McDonell Lake
  - missing site length and width

**Comment by NewGraphEnvironment** [comment]
This is great! Thank you.

>Next time, update/add data in step_4_stream_site_data spreadsheet from fiss and fish cards, then when you run the scripts in extract_inputs.R to populate step_2_fish_coll_data you will have all the correct data.

Another (and potentially preferred option from my perspective) would be to add the data to `form_fiss_site_2023` in 
QQIS, track the changes in version control via `fpr_sp_gpkg_backup`, export to csv with `scripts/fiss_site_tidy.R` (template file is here https://github.com/NewGraphEnvironment/dff-2022/blob/master/scripts/fiss_site_tidy.R but likley now needs updateing) and copy paste over `step_2_fish_coll_data`

**Comment by newgraph-lschick** [comment]
Yes I agree I think that is the best way to do it (see slack message).

**Comment by NewGraphEnvironment** [comment]
logging ad hoc changes required to build reporting objects here as am doing so in `main` fish submission spreadsheet. Related to https://github.com/NewGraphEnvironment/fish_passage_skeena_2023_reporting/issues/102


# step_3_individual_fish_data

- [ ] sampling_method
- [ ] method_number (usually 1 unless multiple methods employed - not the case in 2023)
