### ISSUE TITLE
8478 upstream electrofishing site missing habitat data

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#7]
Was there a habitat card filled out for this site? I can't find any habitat site card info photos besides the one below. Should I add another row in the Q `form_fiss_site` with local name 8478_us_ef and just use channel/wetted widths that Jesse and I got from our upstream survey?

![IMG_2563](https://github.com/NewGraphEnvironment/fish_passage_skeena_2023_reporting/assets/99455166/ebc9d13d-0f27-4066-a0a7-f590363d4f6a)

**Comment by NewGraphEnvironment** [comment]
its 8478_us. Just need to adjust the length to get density I believe. fished it solid

**Comment by Mateo9569** [comment]
Ya, I was just wondering if you had done an additional survey card for the habitat data within your site alone. Jesse and I went all the way to the mapped barrier about 550m upstream.
