### ISSUE TITLE
198217_ds_ef3 - Tributary to Skeena River

### ISSUE THREAD

**Issue by newgraph-lschick** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#84]
- [x] `residual_pool_depth_m` present on fiss site card but missing in form, added to form.
- [x] comments say "fished outlet pool, approx 6m squared" but `Site length` = 6 and `wetted width` = 5.3 which would result in an area of 31.8m squared. This is the second site (other site #78) where Mateo has written the area in the comments but it doesn't align with the measured length and width. Let me know what I should do about this. This is concerning because it will effect the density plots here https://github.com/NewGraphEnvironment/fish_passage_skeena_2023_reporting/blob/main/scripts/01_prep_inputs/0100-extract-inputs.R#L871

**Comment by NewGraphEnvironment** [comment]
ya - good call - lets make the numbers work to get to 6m and keep all the detail we can in the comments

**Comment by newgraph-lschick** [comment]
- [ ] changed site length to 1.2m to attain an area of 6m squared (1.2m x 5.3m = ~6.3m squared). Added to comments " Fiss site card had site length = 6m,  but given the wetted channel width of 5.3m,  an area of 6m squared in impossible.  Changed the site length to 1.2m to attain an area of 6m squared."

**Comment by newgraph-lschick** [comment]
After thinking about this a bit more, for the 2024/25 season maybe we should add a column to the fiss form for the actual electrofishing site length, and could have an option saying "same as site length" which is most common, but would also allow for cases when the ef site length is different than the actually assessed site length . 

I think it would be helpful for resolving cases like this where the length of stream assessed for the habitat assessment is truly 6m but only one small pool was shocked, therefore the ef site length is much less than 6m. Was just reading through https://www2.gov.bc.ca/assets/gov/environment/natural-resource-stewardship/nr-laws-policy/risc/recce2c.pdf and having separate ef and assesment site length would allow for the assessment site length to be closer to "be at least the greater of 100 m or 10 times the bankfull width (Wb). " as seen on page 86. 

We could add an ef site length column and also write it on the fish cards. Can link to https://github.com/NewGraphEnvironment/dff-2022/issues/148 if we want to move forward with this.
