### ISSUE TITLE
Transfer fish data from `fish_data.csv` in onedrive to `habitat_confirmation.xls`

### ISSUE THREAD

**Issue by Mateo9569** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#9]
Just a couple things that need to be done in raw file before the data can be copied and pasted directly into "Step 3"

- Species needs to be changed from acronyms to common name long form. Can import from `fishbc::freshwaterfish` and cross reference
- Grab reference number from step 1 for each site and paste into column in raw file. The macros in `habitat_confirmation.xls` don't allow you to copy and paste special into a sheet unless there are ref numbers. 

I will add a code section for this in the `pit_tags.R` script in the project. And maybe just change the file name to `fish_data_tidy.R`. In the future if we collect fish data digitally we can add additional data wrangling code to this file.

**Comment by NewGraphEnvironment** [comment]
could read in `fish_data.csv` from onedrive directly and `left_join` select columns from`habitat_confirmation.xls` data to the fish data based on site vs copy paste to avoid transcription errors?
