### ISSUE TITLE
14000571_us - Tributary to Houston Tommy Creek

### ISSUE THREAD

**Issue by newgraph-lschick** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#92]
- [ ] fiss site card has a note at the top saying "both us and ds for `14001106`". Does this mean `14000571` and `14001106` have the same habitat data? `14001106_us` has its own site cards so this doesn't really make sense. Maybe this note was a typo and it should say "both us and ds for `14000571`"??

**Comment by NewGraphEnvironment** [comment]
when a survey is done is a location that  is both downstream of one crossing and upstream of another (ie. in between the two crossings) the data applies to the **reporting** for both (in this case - `14000571_us` and `14001106_ds`).  For example - the gradient and channel widths, substrate, etc. downstream of 1401106 is the same as those characteristics upstream of 14000571.

Happens lots and there are quite a few examples in past reports.  Of interest there is an example of how this has been done incorrectly in Peace 2023 - which will need to be fixed.

**Comment by newgraph-lschick** [comment]
Okay yup that makes sense. Turns out there is no `14001106_ds` site so not much of an issue.
