### ISSUE TITLE
123377_ds - Thompson Creek surveyor efficiency sites 

### ISSUE THREAD

**Issue by lucy-schick** [NewGraphEnvironment/fish_passage_skeena_2023_reporting#99]
No action required, just documenting how we dealt with the revisited sites.

Thompson creek downstream sites (`123377_ds_ef1`, `123377_ds_ef2`, `123377_ds_ef3`) were revisited to estimate surveyor efficiency. These sites were enclosed, sample, fish tagged and then returned to the site (sept 14). 24h later (sept 15) the site was revisited, sampled, and the fish were scanned for pit tags to determine surveyor efficiency.

In the `habitat_confirmations` spreadsheet and the `form_fiss_2023.gpkg`, `123377_ds_ef4`, `123377_ds_ef5`, `123377_ds_ef6` reference the revisited sites. We made separate reference numbers and site names for the revisited sites because they have a different sample dates as well as their own temp, cond, and turb data. 

For example, `123377_ds_ef6` is the same site at `123377_ds_ef3`. The site was enclosed, sampled, and the fish returned (`123377_ds_ef3`). 24 hours later the site was resample and the fish were scanned for pit tags to determine surveyor efficiency (`123377_ds_ef6`).

`123377_ds_ef4`, `123377_ds_ef5`, `123377_ds_ef6` were added to the bottom of the spreadsheet so the reference number order was not changed.

Previously, in step 3 (Individual fish data), the different sampling days were differentiated by haul pass = 1 (sept 14) and haul pass = 2 (sept 15), but multiple haul passes are usually used to show that a site is clear of the fish (salvaging) so this was not the best way to document the data.  We changed `123377_ds_ef1`, `123377_ds_ef2`, `123377_ds_ef3` rows which had a `haul pass = 2` to `123377_ds_ef4`, `123377_ds_ef5`, `123377_ds_ef6` respectively, now with haul pass = 1.

**Comment by NewGraphEnvironment** [comment]
same thread here ? https://github.com/NewGraphEnvironment/fish_passage_skeena_2023_reporting/issues/85
